# Generated by Django 5.0 on 2023-12-28 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitantes',
            name='fecha_entrada',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 28, 18, 56, 20, 366758, tzinfo=datetime.timezone.utc)),
        ),
    ]
