# Generated by Django 5.0 on 2023-12-28 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_visitantes_fecha_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitantes',
            name='fecha_entrada',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 28, 19, 0, 18, 443972, tzinfo=datetime.timezone.utc)),
        ),
    ]
