# Generated by Django 5.0 on 2023-12-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_visitantes_fecha_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitantes',
            name='fecha_entrada',
            field=models.DateTimeField(),
        ),
    ]
