# Generated by Django 5.0 on 2024-01-02 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_visitantes_fecha_entrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.visitantes')),
            ],
        ),
    ]
