# Generated by Django 5.0.1 on 2024-01-05 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_visitantes_imagen_delete_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitantes',
            options={'ordering': ['-fecha_entrada']},
        ),
    ]
